config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :resturants do
    resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'resturants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resturant.rb
class Resturant < ApplicationRecord
    has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :resturant
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #issue: stored in version control
    # http_basic_authenticate_with name: "admin", password: "secret"
end

app/controllers/resturants_controller.rb
class ResturantsController < ApplicationController
  before_action :set_resturant, only: [:show, :edit, :update, :destroy]

  # GET /resturants
  # GET /resturants.json
  def index
    @resturants = Resturant.all.order("Created_at DESC")
  end

  # GET /resturants/1
  # GET /resturants/1.json
  def show
  end

  # GET /resturants/new
  def new
    @resturant = Resturant.new
  end

  # GET /resturants/1/edit
  def edit
  end

  # POST /resturants
  # POST /resturants.json
  def create
    @resturant = Resturant.new(resturant_params)

    respond_to do |format|
      if @resturant.save
        format.html { redirect_to @resturant, notice: 'Resturant was successfully created.' }
        # format.json { render :show, status: :created, location: @resturant }
      else
        format.html { render :new }
        # format.json { render json: @resturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resturants/1
  # PATCH/PUT /resturants/1.json
  def update
    respond_to do |format|
      if @resturant.update(resturant_params)
        format.html { redirect_to @resturant, notice: 'Resturant was successfully updated.' }
        format.json { render :show, status: :ok, location: @resturant }
      else
        format.html { render :edit }
        format.json { render json: @resturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resturants/1
  # DELETE /resturants/1.json
  def destroy
    @resturant.destroy
    respond_to do |format|
      format.html { redirect_to resturants_url, notice: 'Resturant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resturant
      @resturant = Resturant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resturant_params
      params.require(:resturant).permit(:name, :description, :location, :phone, :email)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_resturant
    before_action :find_review, only: [:edit, :update, :destroy]
    # @review allows for the respective view to use the object 
    def new
        @review = Review.new
        
    end

    def create
        @review = Review.new(review_params)
        # set review's X_ID to selected X's ID
        @review.resturant_id = @resturant.id
        @review.user_id = current_user.id #will cause issues if unAuth user accesses the new_resturant_review_path

        if @review.save
            redirect_to resturant_path(@resturant)
            else
            render 'new'
        end
    end
    
    def edit
    end

    def update
        @review = Review.find(params[:id])

        if @review.update(review_params)
            redirect_to resturant_path(@resturant)
        else
            render 'edit'
        end
    end
    
    def destroy
        @review.destroy
        redirect_to resturant_path(@resturant)

    end
    
    

    private
        # select review values
        def review_params
            params.require(:review).permit(:rating, :comment)
        end
        # select resturant that is associated with said review
        def find_resturant
            @resturant = Resturant.find(params[:resturant_id])
        end
        
        def find_review
            @review = Review.find(params[:id])
        end
        

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resturants_helper.rb
module ResturantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResturantReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
          <nav class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header">
              <%= link_to "Trap Divisor", root_path, class: "navbar-brand" %>
            </div>

            <ul class="nav navbar-nav">
              <% if user_signed_in? %>
                <li><%= link_to "Sign Out",  destroy_user_session_path, method: :delete %></li>           
                <% else %>
                <li><%= link_to "Sign up",  new_user_registration_path %></li>
                <li><%= link_to "Log In", new_user_session_path %></li>
              <% end %>
            </ul>
   
          </div>
        </nav>

        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <div class="container">
      
      <%= yield %>
    
    </div>
  </body>
<footer >
  <div class="footer-copyright text-center py-3">Copyright © 2019, Flynn Ramos
  </div>
  </footer>
</html>

app/views/resturants/_form.html.erb
<%# used in edit, new %>
<% if user_signed_in? %>
  <%= simple_form_for(@resturant) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name,
        required: true,
        autofocus: true
       %>
      <%= f.input :description, 
        required: true
      %>
      
      <%= f.input :location,
        required: true
      %>

      <%= f.input :phone %>
      <%= f.input :email %>
    </div>

    <div class="form-actions">
      <button type="button" class="btn btn-light"><%= f.button :submit %></button>
    </div>
  <% end %>
<% else %>
  <h1>Nice Try</h1>
<% end %>

app/views/resturants/edit.html.erb
<h1>Editing Resturant</h1>

<%=  render 'form', resturant: @resturant %>

<button type="button" class="btn btn-light"><%= sanitize link_to 'Show', @resturant %></button> |
<button type="button" class="btn btn-light"><%= sanitize link_to 'Back', resturants_path %></button>

app/views/resturants/index.html.erb
<div class="row">
<h1>Resturants:</h1>
</div>


    <% @resturants.each do |resturant| %>
    <div class="row">
      <div class="col">
        <div class="card">
          <h5 class="card-header"><%= resturant.name%></h5>
          <div class="card-body">
            
              <button type="button" class="btn btn-success"><%= sanitize link_to 'Reviews', resturant_path(resturant), class: 'link-to-text-color' %></button>
              <% if user_signed_in? %>
              <div class="btn-group" role="group" aria-label="Basic example">
               <button type="button" class="btn btn-warning"><%= sanitize link_to 'Edit', edit_resturant_path(resturant) %></button>
               <button type="button" class="btn btn-danger"><%= sanitize link_to 'Delete', resturant, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            </div> 
            <% end %>
          </div>
        </div>  
      </div>
    </div>
    <% end %>


<div class="row">
<%# create new resturant %>
<% if user_signed_in? %>
  <button type="button" class="btn btn-light btn-lg"><%= sanitize link_to 'Add Resturant', new_resturant_path %></button>
<% end %>
</div>

app/views/resturants/new.html.erb
 
<% if user_signed_in? %>
    <h1>New Resturant</h1>
    <%= render 'form', resturant: @resturant %>
    <button type="button" class="btn btn-light"><%= sanitize link_to 'Back', resturants_path %></button>
<% else %>
    <button type="button" class="btn btn-light"><%= sanitize link_to 'BACK: Try Again Next Time', resturants_path %></button>
<% end %>

app/views/resturants/show.html.erb
<p>
  <h1><%= sanitize @resturant.name %></h1>
</p>

<p>
  <h4><%= sanitize @resturant.description %></h4>
</p>

<p>
  <strong>Location:</strong>
  <%= sanitize @resturant.location %>
</p>
<%# don't use 'raw' or "html_safe" unless you want to take extra steps to sanatize %>
<%# add functionality for phone link %>
<p>
  <strong>Phone:</strong>
  <%= sanitize @resturant.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= sanitize @resturant.email %>
</p>

<h3>Reviews:</h3>
<% if user_signed_in? %>
    <div>
    <button type="button" class="btn btn-light"><%= sanitize link_to 'Add Review',  new_resturant_review_path(@resturant) %></button>
  </div>
<% end %>

<%# where reviews are rendered %>
<div >
  <%= render  @resturant.reviews %>
</div>
<%# if user signed in is == user who created review then allow edit | Delete %>






<%# reviews go here %>
<%# edit | Delete Review %>

app/views/reviews/_form.html.erb
<%# used in edit, new %>

<% if user_signed_in? %>
  <%= simple_form_for([@resturant, @resturant.reviews.build]) do |f| %>
    <%=  f.error_notification %>
    <%=   f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <span class=""></span><%= f.input :comment,
        required: true,
        autofocus: true
       %>
      <%# <%= f.input :rating %> <%#%>
    </div>
    <div class="form-actions">
      <button type="button" class="btn btn-light"><%= f.button :submit %></button>
    </div>
  <% end %>
<% else %>
    <button type="button" class="btn btn-light"><%= sanitize link_to 'BACK: Try Again Next Time', resturants_path %></button>
<% end %>

app/views/reviews/_review.html.erb
<div class="conatiner border rounded">
    <p class="text-center"><%= sanitize review.comment %></p>
    <%# <p><%= review.rating %> <%#</p> %>


<% if user_signed_in? %>
  <% if review.user_id == current_user.id %>
        <button type="button" class="btn btn-light"><%= sanitize link_to 'Edit',  edit_resturant_review_path(review.resturant, review) %></button> |
        <button type="button" class="btn btn-light"><%=  link_to 'Delete',  resturant_review_path(review.resturant, review), method: :delete, data: {confirm: "Are you sure?"} %></button> 
    <% end %>
<% end %>
</div>

app/views/reviews/edit.html.erb
<% if user_signed_in? %>
  <% if @review.user_id == current_user.id %>
  
      <h1>Edit Review</h1>

      <%= simple_form_for([@resturant, @review]) do |f| %>
        <div class="form-inputs">
          <%= f.input :comment %>
        </div>

        <div class="form-actions">
          <button type="button" class="btn btn-light"><%= f.button :submit %></button>
        </div>

      <% end %>

    <% end %>
<% end %>

app/views/reviews/new.html.erb
<% if user_signed_in? %>
    <h1>New Review</h1>

    <%= render 'form', review: @review %>

<% end %>